-- PRODUCT MANAGEMENT

--Flag products with low stock (e.g., <10 units):
SELECT 
    ProductID,
    ProductName,
    StockQuantity
FROM Products
WHERE StockQuantity < 10
ORDER BY StockQuantity ASC;

--Calculate the total revenue generated by each product:
SELECT 
    p.ProductID,
    p.ProductName,
    SUM(od.Quantity * od.UnitPrice) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY TotalRevenue DESC;

--Find the most frequently ordered products:
SELECT 
    p.ProductName,
    COUNT(od.OrderDetailID) AS OrderCount
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY OrderCount DESC;

--Average stock level by category:
SELECT 
    ProductCategory,
    AVG(StockQuantity) AS AvgStockQuantity
FROM Products
GROUP BY ProductCategory
ORDER BY AvgStockQuantity ASC;
